framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    auto_setup: false
                    queue_name: default
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'App\Messages\PacketMessageInterface': async
