parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    centrifugo:
        class: phpcent\Client
        arguments: ['http://127.0.0.1:8001/api']
        calls:
            - setApiKey: ['1111']

    mqtt.consumer:
        class: PhpMqtt\Client\MqttClient
        arguments: ['144.202.117.148', '1883', 'consumer']

    mqtt.producer:
        class: PhpMqtt\Client\MqttClient
        arguments: [ '144.202.117.148', '1883', 'producer' ]

    App\Command\MqttConsumeCommand:
        arguments:
            $client: '@mqtt.consumer'

    App\Command\MqttProduceCommand:
        arguments:
            $client: '@mqtt.producer'

    App\Controller\ApiController:
        arguments: ['@mqtt.producer']